# Generated by Django 4.2.1 on 2023-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_inventoryproduct_quantity_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'ثبت شد'), ('Ready to send', 'آماده ارسال')], default='Submitted', max_length=20),
        ),
    ]
