# Generated by Django 4.2.1 on 2023-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_remove_inventoryproduct_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
